"""empty message

Revision ID: cfe86acc1522
Revises: c58ff2403032
Create Date: 2020-08-22 04:51:39.357386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe86acc1522'
down_revision = 'c58ff2403032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actors_movie_id_fkey', 'actors', type_='foreignkey')
    op.drop_column('actors', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('actors_movie_id_fkey', 'actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###